### ISSUE TITLE
Tracking: Auto Responses page

### ISSUE THREAD

**Issue by jazeved0** [lucascphillips/aut-bot-app#45]
## Todo
- [x] Implement auto response fetching using old API
  - [x] Consider integrating with new pool-based API?
- [ ] Add data grid component

### Data Grid wishlist
- [ ] Single-click cell editing
- [x] Disable cell selection
- [ ] Text-based fuzzy filters and numeric filters (hide-able with switch)
- [x] Context menu to delete
- [x] View density
- [x] Row selection
- [x] Batch deletion via pop-up header (replace filter view/view density?)
- [ ] Row creation
- [ ] **Reach**: info pane popup on the right openable with context menu action with additional info for auto response (i.e. author, date, id, trigger history (connect with logs?), trigger method, current count)

### Additional UX items
- [ ] Hover on editable inputs having background
- [ ] Syntax highlighting
- [ ] Loading indicators on cells once edited
- [ ] Row disabling during loading/deletion
- [ ] Regex syntax highlighting
- [ ] Emoji display
- [ ] role/channel/mention displays/pool resolution, use skeleton indicator and pool with inline component
- [ ] openable side panel
- [ ] change spacing of context menu
- [ ] add the add row modal (should it be a modal if it's just two fields => maybe just things at the bottom?)
